### PR TITLE
Use default backends when it makes sense

### PR DESCRIPTION
**Pull request by bassosimone**
Basically always except in the regress tests. Refactor regress tests
a bit to make sure it is not an hell to keep them up to date.

### CODE REVIEW

**Comment by hellais** [comment]
The diff looks good to me. I will do some local smoke testing, but it's good to merge for me.

**Comment by bassosimone** [comment]
Thank you!

**Comment by bassosimone** [comment]
@hellais do you think we can bless this?

**Comment by hellais** [comment]
> @hellais do you think we can bless this?

Yes please proceed with merging this.

**Pull request merged**
