### PR TITLE
Allow to run tests using a string as input

### LINKED ISSUE #308: Tests should run with a string as input
It would be nice while defining the test to use a string as input. 

For example [here](https://github.com/measurement-kit/measurement-kit/blob/master/include/measurement_kit/ooni/dns_injection_test.hpp#L30)  we should enable the user to pass a string to the test.

### PR DESCRIPTION
**Pull request by bassosimone**
Closes #308.

### CODE REVIEW

**Comment by bassosimone** [comment]
Putting on hold and removing milestone. This branch does not follow the correct approach, which would be instead of putting the input into the std::istream form which we read usually.

**Comment by hellais** [comment]
I seem to recall you mentioning that you added support for this. I guess not as part of this branch. Can this be closed?

**Comment by hellais** [comment]
Edit: found it!
Does https://github.com/measurement-kit/measurement-kit/pull/1132 superseed this?

**Comment by bassosimone** [comment]
Yes, closing the branch right now, thanks!

**Pull request closed without merging**
