### PR TITLE
Run regress tests through Valgrind

### LINKED ISSUE #99: Automatically run regress tests through Valgrind
It should be useful to run regress tests through Valgrind. To this end, we should create a script that compiles libight using `./configure --disable-shared` and than run each regress test script using `valgrind --error-exitcode=1` so that, if there is a memory error or a leak, `make check` fails.

### PR DESCRIPTION
**Pull request by AntonioLangiu**
Using the variable `TESTS_ENVIRONMENT = valgrind` in Makefile.am we are now able to run regress tests through Valgrind. 

To enable it you should call ./configure with --enable-valgrind and --disable-shared.

To merge this PR we need first to fix the memory leak problems of 3 tests:

* [test/common/delayed_call](https://travis-ci.org/measurement-kit/measurement-kit/jobs/97945929#L1185)
* [test/net/connection](https://github.com/measurement-kit/measurement-kit/issues/191)
* [test/http/stream](https://travis-ci.org/measurement-kit/measurement-kit/jobs/97945929#L1509)

This closes #99

### CODE REVIEW

**Comment by bassosimone** [comment]
Are those errors also reproducible locally?

**Comment by bassosimone** [comment]
What I find annoying of [test/http/stream](https://travis-ci.org/measurement-kit/measurement-kit/jobs/97945929#L1509) is that line numbers are not visible in the stacktrace; however, from the logs it seems that the failing test is on [line 60 of test/http/stream.cpp](https://github.com/measurement-kit/measurement-kit/blob/master/test/http/stream.cpp#L60).

**Comment by bassosimone** [comment]
Looking at test/http/stream.cpp around line 60, I noticed that [stream saves a reference to itself inside a lambda that it owns.](https://github.com/measurement-kit/measurement-kit/blob/master/test/http/stream.cpp#L77). This, as we have seen, creates a reference loop and should prevent the destruction of the stream. If I'm right, adding `stream->on_connect(nullptr);` at end of test could plug the leak.

**Comment by bassosimone** [comment]
Uhm, second reading the code it seems that [emit_error(NoError())](https://github.com/measurement-kit/measurement-kit/blob/master/test/http/stream.cpp#L88) does not cause `stream->on_end()` to be called. We should check whether this is the case. Also, we should reflect on whether this test is still relevant after recent changes made in HTTP code (the pattern of deleting stuff when an error happens is not good and more modern measurement-kit code actually does not use it).

**Comment by AntonioLangiu** [comment]
I will open a new PR to be more clean and readable.

**Pull request closed without merging**
