### PR TITLE
Update http.hpp

### PR DESCRIPTION
**Pull request by helloimcarmine**
I've insert the request functions in the http.hpp file, making them public.

### CODE REVIEW

**Comment by bassosimone** [comment]
I do not understand why travis check here never completed 🎱

**Comment by bassosimone** [comment]
Okay, now I managed to start travis and the build fails. You should recompile the library locally to understand the errors, fix them, and the push changes onto this branch.

**Comment by helloimcarmine** [comment]
In reality I fixed these errors on thursday, but I forgot to push them on the repository 😅 However, I’ve pushed the changes right now!

**Comment by bassosimone** [comment]
Okay! Now the builds goes a bit further, [but it is still failing](https://travis-ci.org/measurement-kit/measurement-kit/jobs/126874984#L1146).

**Comment by helloimcarmine** [comment]
Now I’ve replaced all the calls to request_connect with request_connect_impl.

**Comment by bassosimone** [comment]
Thank you, merging!

**Pull request merged**
