### PR TITLE
http: simplify reader algorithm

### PR DESCRIPTION
**Pull request by bassosimone**
This is, basically, a lighter version of #1345.

### CODE REVIEW

**Comment by bassosimone** [comment]
Moving to v0.9.0, so there is more time to review.

**Comment by hellais** [comment]
This diff looks good to me. I haven't tested it locally yet, but if you don't hear back from me, feel free to merge.

**Comment by bassosimone** [comment]
Thank you!

**Comment by bassosimone** [comment]
Ouch, I need to resolve the conflicts first, will do that later today

**Comment by bassosimone** [comment]
Conflicts solved. The merge commit looks simple enough that it does not require additional review, but perhaps I'd better avoid squashing so we keep it in history.

**Comment by bassosimone** [comment]
Ah, but now it does not build. Umpf.

**Comment by bassosimone** [comment]
Now all conflicts have been solved. Will wait some 24 hours before finally merging.

**Pull request merged**
