### PR TITLE
Run OONI tests in parallel

### PR DESCRIPTION
**Pull request by bassosimone**
Depends on #765

### CODE REVIEW

**Comment by bassosimone** [comment]
@hellais this OONI-related branch is now ready for review! Could you check it out, please?

**Comment by bassosimone** [comment]
oh, right, regress tests are failing because nexa's servers are down for some days :-/

**Comment by hellais** [comment]
Can you rebase this on top of #765, resolve conflicts and I will review it once #765 lands in master?

**Comment by bassosimone** [comment]
@hellais I've merged this branch #765 rather than rebasing. When #765 lands into master, and it is time to merge this one, merging and squashing into master this one should achieve the same effect of rebasing except that the flattening and squashing would be done automatically by github rather than manually by me (we saw recently the perils of rebasing, so I'd rather delegate github)

**Comment by hellais** [comment]
The diff looks good. I will do some testing of the branch and when the integrations tests finish merge it with a squash.

**Comment by hellais** [comment]
LGTM

**Pull request merged**
