### PR TITLE
report: Allow to specify application name and version

### LINKED ISSUE #1088: report: allow to specify application name and version
So that, say, ooniprobe-ios can advertise itself as such

### PR DESCRIPTION
**Pull request by bassosimone**
Closes #1088.

### CODE REVIEW

**Comment by bassosimone** [comment]
@lorenzoPrimi, once `v0.4.0-beta.2` is out, let's remember to use this feature to set the name and version of the applications to the one of `ooniprobe-{android,ios}`!

**Comment by lorenzoPrimi** [comment]
How to do it? tag me when it will be released

**Comment by bassosimone** [comment]
```C++
    .set_options("software_name", "ooniprobe-xx")
    .set_options("software_version", "1.2.3")
```

**Comment by lorenzoPrimi** [comment]
software_version should be the mk version or the app version?

**Comment by bassosimone** [comment]
The app version

**Pull request merged**
