### PR TITLE
Upgrade all vendored dependencies for v0.10.2

### LINKED ISSUE #1792: Update vendored dependencies for v0.10.2
The objective of this issue is to update all the vendored dependencies to the latest version before rolling out a new MK release.

This calls for manually checking for new releases and updating `./script/vendor` scripts.

### PR DESCRIPTION
**Pull request by bassosimone**
Each dependency is in its own commit where I explain why I'm upgrading.

Closes #1792

### CODE REVIEW

**Comment by bassosimone** [comment]
When approved, we can merge. My goal is to release v0.10.2 ASAP such that we can release the new version of OONI mobile. Then I'll also cut a v0.10.3 that fixes AppVeyor and includes more goodies.

**Comment by hellais** [comment]
This appears to be the diff I already reviewed and it still look good to me :).

The appveyor CI is failing, you may or may not want to fix that before merging.

This is good to merge for me though.

**Comment by bassosimone** [comment]
> The appveyor CI is failing, you may or may not want to fix that before merging.

Right. It is failing because something changed in the CI engine and `./configure` fails because `awk` does not find anymore a required DLL. Since this seems much more fundamental than the changes entailed by this PR, and much more toil, I am leaning towards:

1. blessing MK v0.10.2 for OONI mobile's sake ASAP

2. while that is building, invest the required time to unbreak AppVeyor (see #1796)

The current state of affairs of Windows builds is unfortunate and unsatisfactory, sadly.

Thank you for looking into this PR.

**Comment by bassosimone** [comment]
Proceeding with a normal merge, as opposed to squashing, because I'd like to keep history.

**Pull request merged**
