### PR TITLE
Add test_squid_cache_manager test to http invalid request line probes

### PR DESCRIPTION
**Pull request by willscott**
Ref: #1416 

This test makes a request for the 'cache_object://' pseudo-scheme used by squid.
Squid documentation at https://wiki.squid-cache.org/Features/CacheManager
In practice, when squid encounters this request during proxying, it will either
display a cache management directory listing (without any sensitive information),
or will return a 403 error without forwarding it onwards to a remote host.

### CODE REVIEW

**Comment by hellais** [comment]
Remember to also update the test spec and bump the version number.

**Comment by willscott** [comment]
the test at https://github.com/measurement-kit/measurement-kit/blob/master/test/nettests/http_invalid_request_line.cpp seems to continue to pass. I'm not sure I'm going to do a good job at adding a full integration against squid.

**Comment by willscott** [comment]
Is this waiting on me for something?

**Comment by hellais** [comment]
> Is this waiting on me for something?

It's missing a corresponding pull request on ooni-spec updating the test spec for this test: https://github.com/TheTorProject/ooni-spec/blob/master/test-specs/ts-007-http-invalid-request-line.md and the version of the test needs to be bumped as well.

**Comment by willscott** [comment]
Corresponding pull request in omni-spec is made: https://github.com/TheTorProject/ooni-spec/pull/96

**Comment by bassosimone** [comment]
I am going to merge this PR into master.

**Pull request merged**
