### PR TITLE
Faster iOS build by using precompiled dependencies

### PR DESCRIPTION
**Pull request by bassosimone**
1) add set of scripts to precompile dependencies in advance and publish them

2) modify build process to pull precompiled dependencies

3) build/ios/build => build/ios/tmp because imho build/ios/build was confusing

### CODE REVIEW

**Comment by bassosimone** [comment]
cc: @AntonioLangiu @lorenzoPrimi

**Comment by bassosimone** [comment]
This pull request cannot be merged because of a bug. We must at least remove the `.la` files inside `tmp` otherwise the binary bundle downloaded to another computer would not work because the `.la` files hardcode the path of libraries to a nonexistent location. I've manually fixed the binaries that are currently published online but it would be better to automate the process.

**Comment by bassosimone** [comment]
This should be ready for review again, as the above mentioned problem should be fixed now.

**Comment by AntonioLangiu** [comment]
I'm testing this locally

**Comment by AntonioLangiu** [comment]
Ok, I tested it locally and it works. Good work @bassosimone, we need now just 5 minutes to build it!

**Pull request merged**
