### PR TITLE
Change name of Dumb class to Emitter

### PR DESCRIPTION
**Pull request by AntonioLangiu**
Like we said in the #279, I changed the name of the class to a more fitting one.

### CODE REVIEW

**Comment by AntonioLangiu** [comment]
Closes #279

**Comment by bassosimone** [comment]
Could you change your git configuration so that your email is valid? Also, can you squash the commits?

**Comment by bassosimone** [comment]
Nevermind squashing, I will take care of this and also fix your email address in the process. But, please update your git configuration.

**Comment by AntonioLangiu** [comment]
Ah yes.. Sorry :+1:

**Comment by bassosimone** [comment]
Rebased and squashed. Will merge as soon as travis-ci completes. Thank you!

**Pull request merged**
