### PR TITLE
feature: import c-ares 1.13.0

### PR DESCRIPTION
**Pull request by bassosimone**
Required by #1430

### CODE REVIEW

**Comment by bassosimone** [comment]
What I would like the reviewer to do: make some basic proof reading to make sure I didn't do any obvious mistake and attempt to get aquainted with the way in which we manage dependencies. Optionally, given an Unix box (but apparently not Ubuntu on Windows &mdash; hey, who said that that is Unix?), see that `./build/dependency c-ares` works.

**Comment by bassosimone** [comment]
@lorenzoPrimi you can basically avoid 23b100a636e52edd6fe23e732c71d78e7a8a306b, since this is the verbatim import of c-ares sources. All other commits are instead to be reviewed.

**Comment by lorenzoPrimi** [comment]
🐳

**Comment by bassosimone** [comment]
@lorenzoPrimi thanks!

**Pull request merged**
